#!/usr/bin/env python
################################################################################
#
#      Copyright (C) 2016 juztamau5
#      Software License Agreement (MIT License)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#      The above copyright notice and this permission notice shall be included
#      in all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
#
################################################################################

# Usage: get_tap_address
# Prints address of first tap device discovered or returns non-zero

import netifaces
import sys

# Prefix for tap devices, e.g. 'tap' for tap0
TAP_INTERFACE_PREFIX = 'tap'

if __name__ == '__main__':
    interface = None

    for i in netifaces.interfaces():
        if i.startswith(TAP_INTERFACE_PREFIX):
            interface = i
            break

    if interface:
        addresses = netifaces.ifaddresses(interface)

        if netifaces.AF_INET in addresses:
            for address in addresses[netifaces.AF_INET]:
                if address['addr'] == '0.0.0.0':
                    continue

                if address['addr'].startswith('169.254'):
                    continue

                print address['addr']
                sys.exit(0)

    sys.exit(1)
